version: "3"
services:
  socat:
    container_name: socat
    image: alpine/socat
    networks:
      - mynetwork
    ports:
      - 2375:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock
  sonarqube:
    image: sonarqube:lts
    ports:
      - 9000:9000
    networks:
      - mynetwork
    environment:
      - SONAR_FORCEAUTHENTICATION=false
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: services
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: localhost
    ports:
      - 3307:3306
    expose:
      - 3307
    volumes:
      - mysql1:/var/lib/mysql 
    networks:
      - mynetwork

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - 8082:8080
    volumes:
      - jenkinsvol2:/var/jenkins_home
    networks:
      - mynetwork
networks:
  mynetwork:

volumes:
  jenkinsvol2:
  sock1:
  mysql1: